### ISSUE TITLE
ManualInventorySorting Crashing Factorio

### ISSUE THREAD

**Issue by LilacsInMA** [theRustyKnife/ManualInventorySorting#12]
I'm getting the following error when clicking on a chest

The mod Manual Inventory Sorting (2.2.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event manual-inventory-sort::on_gui_opened (ID 95)
__manual-inventory-sort__/control.lua:134: attempt to index global 'SORTABLE' (a nil value)
stack traceback:
	__manual-inventory-sort__/control.lua:134: in function 'sort_buttons_gui'
	__manual-inventory-sort__/control.lua:147: in function <__manual-inventory-sort__/control.lua:144>

**Comment by theRustyKnife** [comment]
Damn i got way too used to strong typing and being able to just rename things :upside_down_face: Anyway this should be fixed now.
